{-# LANGUAGE LambdaCase #-}
-- | Pretty-print "Fuzz.AST" programs as C source for one of two targets:
--
--   * 'TargetRcc'  — C in the rcc subset, no @& 0xFFF@ wrappers.  rcc
--                    truncates overflow at the hardware level, so the only
--                    transformations we apply here are @(unsigned)@ casts
--                    that pin down the *type* of intermediate results so
--                    rcc and host gcc agree on the C semantics.
--   * 'TargetHost' — the same program, but every overflow-prone operation
--                    is additionally wrapped in @& 0xFFF@ so 32-bit gcc
--                    behaves as if it were a 12-bit machine.
--
-- The per-operator decisions ("does this op overflow?", "does its LHS
-- need an @(unsigned)@ cast?", precedence, surface syntax, …) all live in
-- "Fuzz.OpMeta".  This module is just a structural traversal that asks
-- the metadata table what to do at each node.  Adding a new operator is
-- a one-row edit in 'Fuzz.OpMeta.binMeta' — no changes here are needed.
--
-- Why the @(unsigned)@ casts on both targets:
--
-- The dangerous patterns are unary @-@ and @~@ applied to a *signed* @int@
-- intermediate (typically a comparison result), and shift operations whose
-- LHS is signed.  Without a cast:
--
--   * @-(int 1)@ is @int -1@: bit pattern @0xFFF@ on rcc but @0xFFFFFFFF@
--     on host.  When that result then participates in another operation
--     the bit-width difference changes the answer (signed compares,
--     unsigned conversions, masking, etc.).
--   * @int << n@ is undefined behaviour on rcc whenever the result doesn't
--     fit in signed 12-bit @int@; gcc happily produces a 32-bit value.
--
-- Casting the operand to @unsigned@ in *both* outputs forces well-defined
-- modular arithmetic with the platform's @unsigned int@ width on each
-- side: 12-bit on rcc, 32-bit on host.  The host's @& 0xFFF@ then
-- truncates the 32-bit result back to 12 bits, matching rcc's native
-- 12-bit value.
--
-- The two outputs are *observably equivalent* under the contract spelled
-- out in "Fuzz.Gen": all values stay in @[0, 4095]@; the rcc compiler is
-- correct iff the two stdouts match.
module Fuzz.Print
  ( Target (..)
  , renderProgram
  ) where

import Data.Text (Text)
import qualified Data.Text as T

import Fuzz.AST
import Fuzz.OpMeta

data Target = TargetRcc | TargetHost
  deriving (Show, Eq)

-- ---------------------------------------------------------------------------
-- Public entry point

renderProgram :: Target -> Program -> Text
renderProgram tgt (Program decls) =
  T.intercalate "\n" $
       header
    ++ map (renderTop tgt) decls
    ++ [""]
  where
    header =
      [ "// auto-generated by rcc-fuzz; do not edit"
      , "// target: " <> targetTag tgt
      , "#include \"io_include.h\""
      , ""
      ]

targetTag :: Target -> Text
targetTag TargetRcc  = "rcc (unsigned-cast operands, no & 0xFFF wrappers)"
targetTag TargetHost = "host gcc (unsigned-cast operands, every overflowing op masked to 12 bits)"

renderTop :: Target -> TopDecl -> Text
renderTop tgt = \case
  TopGlobal g -> renderGlobal g
  TopFunc f   -> renderFunc tgt f

-- ---------------------------------------------------------------------------
-- Globals

renderGlobal :: GlobalDecl -> Text
renderGlobal (GlobalDecl name ty []) =
  renderTypedName ty name <> ";\n"
renderGlobal (GlobalDecl name ty xs) =
  renderTypedName ty name <> initSuffix ty xs <> ";\n"
  where
    initSuffix (TyArr _ _) ws =
      " = { " <> T.intercalate ", " (map (T.pack . show) ws) <> " }"
    initSuffix _ (w:_) = " = " <> T.pack (show w)
    initSuffix _ []    = ""

-- ---------------------------------------------------------------------------
-- Functions

renderFunc :: Target -> FuncDecl -> Text
renderFunc tgt (FuncDecl name params body) =
  T.unlines
    [ retTy <> " " <> name <> "(" <> renderParams params <> ") {"
    ,   renderBody tgt 1 body
    , "}"
    , ""
    ]
  where
    -- Only `int main()` / `void main()` are blessed by the rcc spec; keep
    -- main typed as `int` (gcc accepts it and emits a clean object).
    -- Helper functions return `unsigned`.
    retTy = if name == "main" then "int" else "unsigned"
    renderParams [] = ""
    renderParams ps = T.intercalate ", " (map renderParam ps)
    renderParam (ty, n) = renderTypedName ty n

renderBody :: Target -> Int -> [Stmt] -> Text
renderBody tgt ind = T.intercalate "\n" . map (renderStmt tgt ind)

-- ---------------------------------------------------------------------------
-- Types

renderTypedName :: Ty -> Text -> Text
renderTypedName TyU n           = "unsigned " <> n
renderTypedName (TyPtr t) n     = renderTypedName t ("*" <> n)
renderTypedName (TyArr sz t) n  = renderTypedName t (n <> "[" <> T.pack (show sz) <> "]")

-- ---------------------------------------------------------------------------
-- Statements

indent :: Int -> Text
indent n = T.replicate n "    "

renderStmt :: Target -> Int -> Stmt -> Text
renderStmt tgt ind = \case
  SDecl v ->
    indent ind <> renderVarDecl tgt v <> ";"
  SExpr e ->
    indent ind <> renderStmtExpr tgt e
  SIf cond t e ->
       indent ind <> "if (" <> renderExpr tgt cond <> ") {\n"
    <> renderBody tgt (ind + 1) t <> "\n"
    <> indent ind <> "}"
    <> (if null e
          then ""
          else " else {\n" <> renderBody tgt (ind + 1) e
               <> "\n" <> indent ind <> "}")
  SWhile cond body ->
       indent ind <> "while (" <> renderExpr tgt cond <> ") {\n"
    <> renderBody tgt (ind + 1) body <> "\n"
    <> indent ind <> "}"
  SFor minit mcond mstep body ->
       indent ind
    <> "for ("
    <> maybe "" (renderVarDecl tgt) minit
    <> "; "
    <> maybe "" (renderExpr tgt) mcond
    <> "; "
    <> maybe "" (renderForStep tgt) mstep
    <> ") {\n"
    <> renderBody tgt (ind + 1) body <> "\n"
    <> indent ind <> "}"
  SBlock body ->
       indent ind <> "{\n"
    <> renderBody tgt (ind + 1) body <> "\n"
    <> indent ind <> "}"
  SReturn Nothing  -> indent ind <> "return;"
  SReturn (Just e) -> indent ind <> "return " <> renderExpr tgt e <> ";"
  SBreak           -> indent ind <> "break;"
  SContinue        -> indent ind <> "continue;"
  SPrint e ->
    -- Splits the value into two 6-bit halves and prints each on its own
    -- line.  Both halves are in [0, 63] so itoa, which treats its input
    -- as `int`, sees a non-negative value on both 12-bit rcc and 32-bit
    -- gcc.
       indent ind
    <> "{ unsigned __fb[16]; unsigned __fv = "
    <> mask12Text tgt (renderExpr tgt e) <> ";"
    <> " itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb);"
    <> " itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }"

-- For-loop step expression.  In host mode, a compound assign or a plain
-- assign whose RHS overflows gets the same desugaring as in 'renderStmtExpr'
-- so the counter never escapes [0, 4095].
renderForStep :: Target -> Expr -> Text
renderForStep tgt e = renderExpr tgt (rewriteCompoundAssignForHost tgt e)

-- A statement-level expression.  For host mode, compound assignments and
-- plain assignments whose RHS overflows get rewritten so the result is
-- masked to 12 bits in a single statement (no trailing @x = x & 0xFFF;@).
renderStmtExpr :: Target -> Expr -> Text
renderStmtExpr tgt e = renderExpr tgt (rewriteCompoundAssignForHost tgt e) <> ";"

-- Rewrite host-only "lvalue mutation" patterns into plain assignments
-- that include a 12-bit mask, so the in-memory value never escapes
-- @[0, 4095]@ on a 32-bit host.
--
--   * @x op= rhs@      →  @x = (x op rhs) & 0xFFF@  (when 'op' overflows)
--   * @x++@ / @++x@    →  @x = (x + 1) & 0xFFF@
--   * @x--@ / @--x@    →  @x = (x - 1) & 0xFFF@
--
-- These rewrites are valid only in *statement* position (i.e. when the
-- expression's value is discarded), so the caller — 'renderStmtExpr'
-- and 'renderForStep' — is the only one that calls into here.  In a
-- value-yielding context (@x = y++@, @f(z++)@) ++ / -- still emit
-- their natural form and the host gets the surrounding @& 0xFFF@ from
-- 'umOverflowsOnHost'.  rcc-target output is unchanged on either path.
rewriteCompoundAssignForHost :: Target -> Expr -> Expr
rewriteCompoundAssignForHost TargetRcc  e = e
rewriteCompoundAssignForHost TargetHost e = case e of
  EAssign aop lhs rhs
    | amOverflowsOnHost (assMeta aop)
    , Just bop <- amBaseBinOp (assMeta aop)
    -- @x op= rhs@  →  @x = (x op rhs) & 0xFFF@
    -- The inner @EBin bop lhs rhs@ already gets the host mask from
    -- 'renderExpr' if it overflows; we don't add a second one here.
    -> EAssign AEq lhs (EBin bop lhs rhs)
  EUn UPreInc  lhs -> EAssign AEq lhs (EBin OAdd lhs (ELit 1))
  EUn UPostInc lhs -> EAssign AEq lhs (EBin OAdd lhs (ELit 1))
  EUn UPreDec  lhs -> EAssign AEq lhs (EBin OSub lhs (ELit 1))
  EUn UPostDec lhs -> EAssign AEq lhs (EBin OSub lhs (ELit 1))
  _ -> e

renderVarDecl :: Target -> VarDecl -> Text
renderVarDecl _   (VarDecl name ty Nothing) =
  renderTypedName ty name
renderVarDecl tgt (VarDecl name ty (Just e)) =
  case ty of
    TyArr _ _ ->
      -- Arrays only get the trivial "{0}" initialiser from the generator.
      renderTypedName ty name <> " = { " <> renderExpr tgt e <> " }"
    _ ->
      renderTypedName ty name <> " = " <> renderExpr tgt e

-- ---------------------------------------------------------------------------
-- Expressions
--
-- Precedence-aware printer.  In TargetHost mode, every overflow-prone
-- node gets its result wrapped in @& 0xFFF@ so gcc's 32-bit arithmetic
-- still produces a 12-bit answer.  The per-op decisions live in
-- "Fuzz.OpMeta".

renderExpr :: Target -> Expr -> Text
renderExpr tgt = go PAss
  where
    paren p ctx s
      | p < ctx   = "(" <> s <> ")"
      | otherwise = s

    -- Cast a sub-expression's textual rendering to @unsigned@.  The
    -- operand goes inside a fresh paren pair so we never have to think
    -- about precedence at the cast boundary.
    castU s = "(unsigned)(" <> s <> ")"

    go _ (ELit n)  = T.pack (showLit n)
    go _ (EVar n)  = n
    go ctx (EBin op a b) =
      let m   = binMeta op
          p   = bmPrec m
          lhs = if bmNeedsUnsignedLhs m
                  then castU (go PAss a)
                  else go p a
          raw = paren p ctx (lhs <> " " <> bmSym m <> " " <> go (succP p) b)
      in if tgt == TargetHost && bmOverflowsOnHost m
           then "((" <> raw <> ") & 0xFFF)"
           else raw
    go ctx (EUn op a) =
      let m   = unMeta op
          p   = umPrec m
          arg = if umNeedsUnsignedCast m
                  then castU (go PAss a)
                  else go p a
          raw = case op of
            UPostInc -> paren p ctx (go p a <> umSym m)
            UPostDec -> paren p ctx (go p a <> umSym m)
            _        -> paren p ctx (umSym m <> arg)
      in if tgt == TargetHost && umOverflowsOnHost m
           then "((" <> raw <> ") & 0xFFF)"
           else raw
    go ctx (EAssign op lhs rhs) =
      let s = amSym (assMeta op)
      in paren PAss ctx (go PUn lhs <> " " <> s <> " " <> go PAss rhs)
    go _ (ECall name args) =
      name <> "(" <> T.intercalate ", " (map (go PAss) args) <> ")"
    go _ (EIndex a i) =
      go PAtom a <> "[" <> go PAss i <> "]"
    go ctx (EDeref e) =
      paren PUn ctx ("*" <> go PUn e)
    go ctx (EAddr e) =
      paren PUn ctx ("&" <> go PUn e)
    go ctx (EIfE c t e) =
      -- ?: associates right-to-left in C: a ? b : c ? d : e parses as
      -- a ? b : (c ? d : e).  We render the condition tighter than POr
      -- (per C precedence) and the branches at the assignment level
      -- (loosest), so a nested ?: in either branch needs no extra parens.
      let raw = go PLOr c <> " ? " <> go PAss t <> " : " <> go PAss e
      in paren PCond ctx raw

    showLit n
      | n >= 0 && n <= 9 = show n
      | otherwise        = "0x" ++ pad (toHex n)
      where
        toHex 0 = "0"
        toHex k = let (q, r) = k `divMod` 16
                      d = if r < 10 then toEnum (fromEnum '0' + r)
                                    else toEnum (fromEnum 'A' + r - 10)
                  in (if q == 0 then "" else toHex q) ++ [d]
        pad s = if length s < 1 then "0" ++ s else s

-- A target-aware mask-to-12-bits wrapper for a precomputed string.  We
-- emit the @& 0xFFF@ on both targets so the two C files stay structurally
-- close (the inner-op masks are the only difference).  rcc is happy with
-- the redundant mask; its constant folder removes it.
mask12Text :: Target -> Text -> Text
mask12Text _ s = "((" <> s <> ") & 0xFFF)"
