// auto-generated by rcc-fuzz; do not edit
// target: rcc ()unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

int main() {
    unsigned v0 = 0xF02;
    unsigned v1 = (unsigned)(v0 == v0) << 1;
    unsigned v2 = (unsigned)(0xCE2 | v1) << 7;
    unsigned v3[3] = { 0 };
    {
        v0 = 0x9AF;
    }
    v0 *= v2;
    {
        unsigned v5 = 0;
        for (unsigned v4 = 0; v5 < 6 & v4 < 5; v4 = (unsigned)(v4) + 1) {
            break;
            v5 = (unsigned)(v5) + 1;
        }
    }
    { unsigned __fb[16]; unsigned __fv = ((v2) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v0) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = (((unsigned)(0x495) << 4) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0x40 & (0x63 ? v1 : 0x40C)) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


