// auto-generated by rcc-fuzz; do not edit
// target: rcc (unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

unsigned f0(unsigned p0, unsigned p1, unsigned p2) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0[3] = { 0 };
    unsigned v1[4] = { 0 };
    p0 = p1;
    {
        unsigned v2 = 0;
        while (v2 < 6 & (p0 || p2) == p0) {
            p0++;
            p2 |= p0;
            v2 = (unsigned)(v2) + 1;
        }
    }
    {
        unsigned v3 = 0;
        while (v3 < 6 & 0xA9D > (p0 && p0)) {
            break;
            p1 *= 0xB28;
        }
            v3 = (unsigned)(v3) + 1;
    }
    p0 |= 0xCDE;
    return (unsigned)(p0) + ((unsigned)(p1) + p2);
}


int main() {
    unsigned v0 = (unsigned)(0x53F && 0x360) - ((unsigned)(0xB5) + 0xE34);
    unsigned v1[4] = { 0 };
    unsigned v2 = v0 && v0 & 0x578;
    unsigned v3 = ~(unsigned)(0xBE1);
    {
        unsigned v4 = 0;
        while (v4 < 6 & (0xEAD | v2) <= v0) {
            {
                unsigned v6 = 0;
                for (unsigned v5 = 0; v6 < 6 & v5 < 5; v5 = (unsigned)(v5) + 1) {
                    if (v5) {
                        v0 = 0xE22;
                    }
                    break;
                    v6 = (unsigned)(v6) + 1;
                }
            }
            unsigned v7 = 0xAB;
            v4 = (unsigned)(v4) + 1;
        }
    }
    {
        {
            unsigned v9 = 0;
            for (unsigned v8 = 0; v9 < 6 & v8 < 5; v8 = (unsigned)(v8) + 1) {
                if (f0(0x556 != 0x7AA, 0x65D, !v3)) {
                    v3 += v2;
                }
                v9 = (unsigned)(v9) + 1;
            }
        }
        v0 |= 0x460;
    }
    { unsigned __fb[16]; unsigned __fv = (((unsigned)(v3) * 0x5F1 >= 0x525) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0xCDF) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v3 <= (0x47C ? v3 : v3)) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v0) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


