// auto-generated by rcc-fuzz; do not edit
// target: rcc ()unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

int main() {
    unsigned v0 = (unsigned)(0xAC3) << 0xB > (0x7A != 0x6A0);
    unsigned v1 = (unsigned)(v0) - (v0 <= v0);
    unsigned v2 = (unsigned)(v1) << 9 < 0x7F3;
    unsigned v3 = (unsigned)(v2) >> 0;
    {
        unsigned v5 = 0;
        for (unsigned v4 = 0; v5 < 6 & v4 < 6; v4 = (unsigned)(v4) + 1) {
            break;
            v1 = (unsigned)(v4) - ((unsigned)(0x8F9) << 1);
            v5 = (unsigned)(v5) + 1;
        }
    }
    v3 = 0x814;
    v2 = 0x300 | (unsigned)(v2) - 0xDC;
    { unsigned __fb[16]; unsigned __fv = ((0xBBB < 0x52D) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v3) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((!(0x4B9 != 0xEBF)) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0xEF0) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


