// auto-generated by rcc-fuzz; do not edit
// target: rcc (unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

unsigned f0(unsigned p0, unsigned p1, unsigned p2) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = 0x638;
    if (v0 < 0x100) {
        return 0xE80;
    }
    {
        v0 -= 0xCFD;
        unsigned v1 = (unsigned)(0xDA7) << 3 || (0x1AC || p1);
        unsigned v2 = (unsigned)(v0) << 1;
    }
    p1 = (unsigned)(p1) << 9 == p1;
    return (unsigned)(p0) + ((unsigned)(p1) + p2);
}


unsigned f1(unsigned p0, unsigned p1, unsigned p2) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = (unsigned)(0x355) * p1 < (unsigned)(0xA61) * 0x96E;
    unsigned v1 = v0;
    unsigned v2[4] = { 0 };
    if (p1 < 0x100) {
        return p0;
    }
    v1 -= p1;
    {
        unsigned v4 = 0;
        for (unsigned v3 = 0; v4 < 6 & v3 < 5; v3 = (unsigned)(v3) + 1) {
            break;
            v4 = (unsigned)(v4) + 1;
        }
    }
    p0++;
    return (unsigned)(p0) + ((unsigned)(p1) + p2);
}

int main() {
    unsigned v0 = -(unsigned)(0xE16 | 0xD70);
    unsigned v1 = 0x84D;
    unsigned v2 = v1;
    unsigned v3[2] = { 0 };
    {
        v2++;
    }
    v2 = f1(v0, v0, 0x447) <= (v1 ? v2 : 0x4DD);
    if (v1) {
        if (!0x5C0) {
            v1 = v2 <= (v2 || v1);
            {
                unsigned v4 = 0;
                while (v4 < 6 & v2) {
                    --v0;
                    {
                        {
                            unsigned v5 = 0;
                            while (v5 < 6 & (v0 && 0xF5A && v1 & 0x474)) {
                                v0 = (unsigned)(v0) - (0x32C ^ v0);
                                v5 = (unsigned)(v5) + 1;
                            }
                        }
                        v0 = v1;
                    }
                    v4 = (unsigned)(v4) + 1;
                }
            }
        } else {
            if ((unsigned)(0xD92) >> 2) {
                v0 = (unsigned)(v2) >> 1;
            }
        }
    } else {
        v0 &= v2;
    }
    v2++;
    { unsigned __fb[16]; unsigned __fv = ((v1) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v0 != v0 & v3[1]) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v0 < (unsigned)(0x380) << 0xB) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = (((unsigned)(0x3A3) >> 6 ? 0x38F >= v1 : 0x270) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


