// auto-generated by rcc-fuzz; do not edit
// target: rcc ()unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

unsigned f0(unsigned p0) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = p0;
    if (v0 < 0x100) {
        return v0 || (unsigned)(0x462) << 9;
    }
    v0 += p0;
    if ((unsigned)(0xA40) + 0xBA4) {
        {
            unsigned v2 = 0;
            for (unsigned v1 = 0; v2 < 6 & v1 < 3; v1 = (unsigned)(v1) + 1) {
                v0++;
                v1 = (unsigned)(p0) << 6;
                v2 = (unsigned)(v2) + 1;
            }
        }
        v0 = 0x14C <= 0xCC8;
    }
    return p0;
}


unsigned f1(unsigned p0) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = 0xC8E > 0x664;
    if (p0 < 0x100) {
        return (unsigned)(0x38E) * 0x222 < f0(v0);
    }
    v0++;
    p0 -= v0;
    v0 = v0;
    return p0;
}


int main() {
    unsigned v0 = 0x164;
    unsigned v1 = 0xAC8;
    unsigned v2 = (unsigned)(0x40F) >> 8 > v0;
    unsigned v3 = v0;
    if (0xC26) {
        {
            unsigned v5 = 0;
            for (unsigned v4 = 0; v5 < 6 & v4 < 3; v4 = (unsigned)(v4) + 1) {
                {
                    unsigned v7 = 0;
                    for (unsigned v6 = 0; v7 < 6 & v6 < 3; v6 = (unsigned)(v6) + 1) {
                        if (f0((unsigned)(v4) >> 0xA)) {
                            if ((unsigned)(v3 || v6) - (0x309 || v2)) {
                                unsigned v8 = v3;
                            } else {
                                v4 &= v3;
                                v6 *= v0;
                            }
                        } else {
                            v2++;
                        }
                        break;
                        v7 = (unsigned)(v7) + 1;
                    }
                }
                --v2;
                v5 = (unsigned)(v5) + 1;
            }
        }
    } else {
        v3 = (v2 && 0xB40) <= 0x93B;
        v2 = 0xAC1;
    }
    v1 -= v1;
    if (0xC4E != v0 == (0x963 ^ 0xC81)) {
        v3 = f0(v0);
    }
    ++v1;
    { unsigned __fb[16]; unsigned __fv = (((unsigned)(f0(v0)) >> 6) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v0 < 0x219 | 0x25F) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0x133) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v2 >= (unsigned)(v0) << 0xB) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


