// auto-generated by rcc-fuzz do not edit
// target: rcc (unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

unsigned f0(unsigned p0, unsigned p1, unsigned p2) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = (unsigned)(0x8FF) >> 0xA;
    v0 &= p0;
    p0 = (unsigned)(p0 ? 0xD6F : 0x5AF) << 0xB;
    v0 = (unsigned)(!p0) * ((unsigned)(0x5BF) << 6);
    {
        unsigned v2 = 0;
        for (unsigned v1 = 0; v2 < 6 & v1 < 4; v1 = (unsigned)(v1) + 1) {
            break;
            v1 &= p1;
            v2 = (unsigned)(v2) + 1;
        }
    }
    return (unsigned)(p0) + ((unsigned)(p1) + p2);
}


int main() {
    unsigned v0 = (unsigned)((unsigned)(0x69E) + 0x283) << 2;
    unsigned v1 = 0x670;
    unsigned v2 = (unsigned)(0xF12) << 6 & 0x4C6;
    unsigned v3 = v1;
    if (0x45C) {
        v2 = (unsigned)(v2) >> 0xA;
        --v2;
    } else {
        v2 = 0xEBB ? v1 : v3;
    }
    v0 = (unsigned)(v1) * ((unsigned)(v0) >> 8);
    --v1;
    v2 = f0(0x40C ? v1 : v2, f0(v1, v2, 0x41), 0x553 & v3);
    { unsigned __fb[16]; unsigned __fv = ((v0) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((f0(0xD96 ? 0xA72 : v1, v2 ^ 0xBD0, v3)) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((f0(v3, v2, v2) == v1) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v3) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


