// auto-generated by rcc-fuzz; do not edit
// target: rcc (unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

unsigned f0(unsigned p0, unsigned p1) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = (unsigned)(p0 <= p0) << 7;
    unsigned v1 = (unsigned)(0x7FC) - p0;
    {
        {
            unsigned v3 = 0;
            for (unsigned v2 = 0; v3 < 6 & v2 < 2; v2 = (unsigned)(v2) + 1) {
                {
                    {
                        unsigned v5 = 0;
                        for (unsigned v4 = 0; v5 < 6 & v4 < 6; v4 = (unsigned)(v4) + 1) {
                            break;
                            p0++;
                            v5 = (unsigned)(v5) + 1;
                        }
                    }
                    if (0x3A7 || p1 & p1) {
                        v0 = !-(unsigned)(0xDE2);
                        {
                            unsigned v7 = 0;
                            for (unsigned v6 = 0; v7 < 6 & v6 < 2; v6 = (unsigned)(v6) + 1) {
                                if ((unsigned)((unsigned)(0xAD1) >> 6) >> 5) {
                                    v1++;
                                    v6 = p1 > (unsigned)(0xFF3) >> 0xB;
                                }
                                --v1;
                                v7 = (unsigned)(v7) + 1;
                            }
                        }
                    } else {
                        v1 = p0;
                    }
                    if ((unsigned)(v1) * (v2 || v1)) {
                        if ((unsigned)(p0) >> 3 || v1) {
                            v1 = v2 | p0 ? 0x62D ? v2 : 0x7BC : 0x7D4;
                            p1 = p0;
                        }
                        ++p0;
                    } else {
                        break;
                    }
                }
                v1 += 0x949;
                v3 = (unsigned)(v3) + 1;
            }
        }
        if (-(unsigned)(v0 != 0xF30)) {
            v1 ^= v0;
            p1 = 0x610;
        } else {
            {
                v1 = p0;
                p0--;
            }
            p0 |= p1;
        }
        ++p0;
    }
    if ((unsigned)(v0 & 0xEE1) + p0) {
        p0 = v1;
    }
    if ((unsigned)(p1) >> 9) {
        p0 = f0((unsigned)(p0) + 1, p1);
        p0 &= p1;
    } else {
        {
            unsigned v9 = 0;
            for (unsigned v8 = 0; v9 < 6 & v8 < 6; v8 = (unsigned)(v8) + 1) {
                p0--;
                v9 = (unsigned)(v9) + 1;
            }
        }
    }
    return (unsigned)(p0) + p1;
}


int main() {
    unsigned v0 = 0x2EF;
    unsigned v1 = 0xC67;
    unsigned v2 = (unsigned)(v1) << 7 ? (unsigned)(0x35) << 3 : v1 >= v0;
    unsigned v3 = v2 == v1;
    {
        unsigned v5 = 0;
        for (unsigned v4 = 0; v5 < 6 & v4 < 3; v4 = (unsigned)(v4) + 1) {
            break;
            v5 = (unsigned)(v5) + 1;
        }
    }
    if ((unsigned)(v1) >> 5) {
        {
            unsigned v6 = 0;
            while (v6 < 6 & (0xE7A && v0)) {
                if (v1) {
                    ++v0;
                }
                v3 = f0(v2, v2) <= v3;
                v6 = (unsigned)(v6) + 1;
            }
        }
    } else {
        --v3;
    }
    {
        unsigned v8 = 0;
        for (unsigned v7 = 0; v8 < 6 & v7 < 5; v7 = (unsigned)(v7) + 1) {
            v7 += 0xF82;
            ++v7;
            v8 = (unsigned)(v8) + 1;
        }
    }
    {
        unsigned v10 = 0;
        for (unsigned v9 = 0; v10 < 6 & v9 < 2; v9 = (unsigned)(v9) + 1) {
            if ((unsigned)(v1) << 0) {
                v0 = (unsigned)(~(unsigned)(v3)) * ((unsigned)(v0) << 1);
            } else {
                --v0;
            }
            v10 = (unsigned)(v10) + 1;
        }
    }
    { unsigned __fb[16]; unsigned __fv = ((v3) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = (((unsigned)(0x59B ? v1 : v2) - ((unsigned)(v0) >> 5)) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0x840) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = (((v1 ? 0x76B : 0x2A0) ? 0x303 ? v2 : v1 : 0x89B) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


