// auto-generated by rcc-fuzz; do not edit
// target: rcc (unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

unsigned f0(unsigned p0, unsigned p1) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = 0x8B;
    v0 = v0 && p0;
    p0 = (p0 || p0) & p0;
    if ((unsigned)((unsigned)(p0) >> 4) << 4) {
        {
            p1 = v0;
            if (0xA2D) {
                --p0;
                p0 &= 0xC5;
            }
        }
    }
    p1 = v0;
    return (unsigned)(p0) + p1;
}

unsigned f1(unsigned p0, unsigned p1) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = p1;
    unsigned v1 = (0xEC3 ^ 0x49C) >= (unsigned)(p0) - v0;
    {
        unsigned v3 = 0;
        for (unsigned v2 = 0; v3 < 6 & v2 < 6; v2 = (unsigned)(v2) + 1) {
            break;
            v3 = (unsigned)(v3) + 1;
        }
    }
    p1++;
    return (unsigned)(p0) + p1;
}


int main() {
    unsigned v0[2] = { 0 };
    unsigned v1 = (unsigned)(0x2B3) - 0x1B7 < (0x506 ? 0x56F : 0xA73);
    unsigned v2 = v1;
    unsigned v3 = (unsigned)(v0[0]) << 8;
    if ((unsigned)(v0[1]) >> 0) {
        {
            {
                unsigned v4 = 0;
                while (v4 < 6 & 0x50A) {
                    {
                        v1 |= 0x8D4;
                        v3 = v3;
                    }
                    v3 &= v2;
                    v4 = (unsigned)(v4) + 1;
                }
            }
        }
    } else {
        v1 &= v3;
    }
    {
        v1 |= 0xE08;
        v1 &= v1;
        v2 = ~(unsigned)(v3);
    }
    { unsigned __fb[16]; unsigned __fv = ((f1(0x76B, (unsigned)(0x95F) << 4)) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v3) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = (((unsigned)(v1) * v2) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0x78) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


