// auto-generated by rcc-fuzz; do not edit
// target: rcc (unsigned-cast operands, no & 0xFFF wrappers)

#include "io_include.h"
int main() {
    unsigned v0 = (0x169 ? 0xADF : 0xCB1) <= (0x93A && 0xCF7);
    unsigned v1 = 0xD02 > (0x41 & v0);
    unsigned v2[2] = { 0 };
    unsigned v3 = (unsigned)(v0 ? v0 : 0x3B3) >> 8;
    v1 = v3;
    v1--;
    if ((0x6D3 ? v1 : v1) ? (unsigned)(0xF35) >> 0 : (unsigned)(0x8B7) >> 6) {
        {
            unsigned v5 = 0;
            for (unsigned v4 = 0; v5 < 6 & v4 < 5; v4 = (unsigned)(v4) + 1) {
                v1 = (unsigned)((unsigned)(0xFF3) >> 8) << 2;
                break;
                v5 = (unsigned)(v5) + 1;
            }
        }
    }
    unsigned v6 = (v1 || 0x59E) <= (unsigned)(0xC4A) + v3;
    { unsigned __fb[16]; unsigned __fv = ((v3) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v0) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = (((unsigned)(v1 ^ 0x24D) << 8) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0x8DA) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


