// auto-generated by rcc-fuzz; do not edit
// target: rcc (unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

unsigned f0(unsigned p0, unsigned p1, unsigned p2) {
    if (p0 >= 4) {
        return 0;
    }
    if (p0 < 0x100) {
        return 0xA00;
    }
    {
        {
            unsigned v1 = 0;
            for (unsigned v0 = 0; v1 < 6 & v0 < 3; v0 = (unsigned)(v0) + 1) {
                if ((unsigned)(0x8A3) * p0) {
                    if ((unsigned)(p2 && p0) + ((unsigned)(p2) - p2)) {
                        p0 = p2;
                        p1 = 0x9D8 == f0((unsigned)(p0) + 1, p1, 0x9F5);
                    }
                    {
                        p0 = !p2 < (0xBE3 != 0x20C);
                        p2 |= p1;
                    }
                }
                v1 = (unsigned)(v1) + 1;
            }
        }
        p1 = p1;
    }
    return (unsigned)(p0) + ((unsigned)(p1) + p2);
}


unsigned f1(unsigned p0, unsigned p1) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = (unsigned)((unsigned)(p1) << 5) >> 8;
    return (unsigned)(p0) + p1;
}


int main() {
    unsigned v0[3] = { 0 };
    unsigned v1 = 0x666;
    unsigned v2 = 0xDB5;
    unsigned v3 = 0x98B;
    {
        unsigned v5 = 0;
        for (unsigned v4 = 0; v5 < 6 & v4 < 6; v4 = (unsigned)(v4) + 1) {
            break;
            v5 = (unsigned)(v5) + 1;
        }
    }
    {
        if ((unsigned)((unsigned)(v3) << 3) << 6) {
            unsigned v6[3] = { 0 };
        }
        v3 += v2;
        v1 = v0[1];
    }
    { unsigned __fb[16]; unsigned __fv = ((0xE83) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((-(unsigned)(0x724)) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((~(unsigned)(0x6A6 >= 0xC7B)) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0x242) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


