// auto-generated by rcc-fuzz; do not edit
// target: rcc (unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

unsigned f0(unsigned p0, unsigned p1) {
    if (p0 >= 4) {
        return 0;
    }
    if (p0 < 0x100) {
        return (unsigned)(!p1) << 8;
    }
    if (p0) {
        p1 = (unsigned)(p1 >= p1) - (p0 && p0);
        p0 = p1;
    }
    p0 = 0xFC9;
    return (unsigned)(p0) + p1;

}

int main() {
    unsigned v0 = 0x52A;
    unsigned v1 = !v0;
    unsigned v2[4] = { 0 };
    unsigned v3 = 0x8E;
    {
        {
            unsigned v5 = 0;
            for (unsigned v4 = 0; v5 < 6 & v4 < 5; v4 = (unsigned)(v4) + 1) {
                break;
                v4 *= v0;
                v5 = (unsigned)(v5) + 1;
            }
        }
    }
    v3--;
    { unsigned __fb[16]; unsigned __fv = ((v3) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = (((unsigned)(v0 && 0xB68) << 3) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v2[0]) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = (((unsigned)(v0) >> 6 ? v3 : (unsigned)(v3) >> 1) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


