// auto-generated by rcc-fuzz; do not edit
// target: rcc ()unsigned-cast operands, no & 0xFFF wrappers)
#include "io_include.h"

unsigned f0(unsigned p0) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = (unsigned)(0xCC2) << 5;
    unsigned v1 = p0;
    unsigned v2[3] = { 0 };
    {
        unsigned v3 = 0;
        while (v3 < 6 & f0((unsigned)(p0) + 1)) {
            v1 = (unsigned)((unsigned)(0xAAF) >> 4) * v1;
            v3 = (unsigned)(v3) + 1;
        }
    }
    v1 = (unsigned)(0x525) - (0x353 != v1);
    return p0;
}


unsigned f1(unsigned p0) {
    if (p0 >= 4) {
        return 0;
    }
    unsigned v0 = p0 <= (p0 || p0);
    {
        if ((unsigned)(p0) << 0 ? 0xD02 ? v0 : v0 : -(unsigned)(0xE00)) {
            v0 = (unsigned)(0x745 | v0) * 0x323;
        } else {
            p0 -= 0xE87;
            v0 &= v0;
        }
    }
    {
        v0 = (unsigned)(0x9E8) << 2 != (v0 ^ p0);
        p0 = v0;
        if ((unsigned)(0xAC6) << 0xB & (0x778 || 0xBE5)) {
            v0 |= 0x60F;
        }
    }
    return p0;
}


int main() {
    unsigned v0 = f1((unsigned)(0x257) * 0xB72);
    unsigned v1 = v0;
    unsigned v2 = !0x49A | v1;
    unsigned v3 = (v2 ? v2 : 0xD96) != (unsigned)(v0) - 0x63A;
    v3 = 0xD80;
    {
        {
            unsigned v4 = 0;
            while (v4 < 6 & f1((unsigned)(0xFD9) >> 5)) {
                {
                    unsigned v6 = 0;
                    for (unsigned v5 = 0; v6 < 6 & v5 < 3; v5 = (unsigned)(v5) + 1) {
                        unsigned v7 = 0x2E3;
                        v1 -= v0;
                        v6 = (unsigned)(v6) + 1;
                    }
                }
                v4 = (unsigned)(v4) + 1;
            }
        }
        ++v1;
    }
    {
        unsigned v8 = 0;
        while (v8 < 6 & (v3 ? 0x190 : 0x5EC) <= (v0 & 0xD6)) {
            {
                unsigned v10 = 0;
                for (unsigned v9 = 0; v10 < 6 & v9 < 2; v9 = (unsigned)(v9) + 1) {
                    ++v2;
                    v10 = (unsigned)(v10) + 1;
                }
            }
            v1 = (unsigned)(f1(0x166)) << 9;
            v8 = (unsigned)(v8) + 1;
        }
    }
    {
        unsigned v12 = 0;
        for (unsigned v11 = 0; v12 < 6 & v11 < 5; v11 = (unsigned)(v11) + 1) {
            break;
            v12 = (unsigned)(v12) + 1;
        }
    }
    { unsigned __fb[16]; unsigned __fv = ((v1) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0xB43) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((0x318 > v0 || (unsigned)(0xC8C) >> 6) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    { unsigned __fb[16]; unsigned __fv = ((v1 == v0) & 0xFFF); itoa((int)((__fv >> 6) & 0x3F), (int *)__fb); puts((int *)__fb); itoa((int)(__fv & 0x3F),       (int *)__fb); puts((int *)__fb); }
    return 0;
}


